#!/usr/bin/env bash
# Configures an Ubuntu server with the following requirements:
# 	     - localhost resolves to 127.0.0.2
#	     - facebook.com resolves to 8.8.8.8

TMP_FILE=/tmp/hosts.tmp
sudo cp /etc/hosts $TMP_FILE
sed -i s/127.0.0.1/127.0.0.2/ $TMP_FILE
echo -e "8.8.8.8\tfacebook.com" >> $TMP_FILE

if [ -f $TMP_FILE ]; then
    sudo cat $TMP_FILE > /etc/hosts
    rm $TMP_FILE
else
    echo "Error: Failed to modify hosts file"
    exit 1
fi
